### PR TITLE
Gamepad mapping update

### PR DESCRIPTION
**Pull request by ThomasFOG**
This is a general update / clean up of the gamepad mappings, based on the latest https://github.com/gabomdq/SDL_GameControllerDB

### CODE REVIEW

**Comment by ThomasFOG** [comment]
Bump @dellis1972 :)

**Comment by dellis1972** [comment]
@mrhelmut has this been tested with the Native backend as well as the SDL one?

**Comment by ThomasFOG** [comment]
I've only added new ones & removed a wrong PS4 GUID. If they (don't) work, this PR shouldn't change anything.

**Comment by dellis1972** [comment]
Cool. merging

**Pull request merged**
